### ISSUE TITLE
Long URLs that are truncated in the CMS UI result in invalid copy text

### ISSUE THREAD

**Issue by dizzystuff** [xddesigners/silverstripe-urlsegment-copy-button#1]
Love this little mod a lot! Realised this week that when the CMS UI truncates a long URL, the Copy Button is retrieving the anchor element's innerHTML rather than the href value, which means that an invalid URL string is being copied to the clipboard.

![sshot](https://user-images.githubusercontent.com/576903/176800230-d39f3c33-69b6-47f0-88bc-4025df6e135c.png)

For example, in this screenshot, clicking COPY will copy this string to the clipboard `...-and-trade-addressing-gender-disparity-in-pacific-trade` rather than the full URL.

**Comment by RVXD** [comment]
Nice catch! Thanks for the fix.

**Comment by dizzystuff** [comment]
@RVXD when you have a chance would you mind adding a tag for the project, so we can include this in composer via tag/version number rather than the more open dev-main constraint?

**Comment by RVXD** [comment]
Just added a v1.0.0 tag!

**Comment by dizzystuff** [comment]
Awesome, thanks again!
